full_name= input("what is your name?")
age = input("How old are you: ")
gender = input("Are  you male / female: ")
address= input("Where do you live: ")
qualification = input("What is your qualification: ")
marital_status = input("What is your marital status: ")
telephone_number= input("What is your phone number: ")
email_address= input("Email: ")
print(f"Hey,{full_name} you are {age} and you live at {address} your {qualification} and you are {marital_status} you can leave your {telephone_number},{email_address} with us for more information and feed back ")